### ISSUE TITLE
output='DataFrame' forlenger kjøretiden betydelig

### ISSUE THREAD

**Issue by kmunve** [ragnarekker/varsomdata#3]
Når jeg bytter output fra 'List' til 'DataFrame', for klassen 'AvalancheDanger' i mitt tilfelle, bruker skriptet rundt 15 min istedet for 30 sec.

**Comment by kmunve** [comment]
Det var faktisk endring til lang_key=0 som økte tiden ???
Output='DataFrame' krever en endring i _make_eval3_conform

**Comment by ragnarekker** [comment]
Kun lang_key 1 og 2 støttes av regobs-api. Har laget en sjekk som sikrer at spørringen defaulter til engelsk om ikke 1 eller 2 gis.

https://github.com/ragnarekker/varsomdata/blob/regobs-v4-support/varsomdata/getobservations.py#L315
